### ISSUE TITLE
What do you dislike about Python? 

### ISSUE THREAD

**Issue by sopticek** [s3rvac/AMA#2]

**Comment by s3rvac** [comment]
In short:
1. Private/internal visibility is based on an ugly looking convention: prefixing variable/class/function names with underscores.
2. Global Interpreter Lock (GIL), which forces you to use processes instead of threads where threads in other languages would be a better choice. This is not a Python property per se as it is related to the default CPython _implementation_.
3. `super()`. Contrary to general beliefs, it does not always have to call a base class, its use is syntactically different from common Python code, it requires consistent use across the whole class hierarchy, and does not work for operators.
4. Inconsistent naming of identifiers in the standard library (some are in `camelCase`, some in `snake_case`, and some are without any word separator.
5. Unsystematic documentation. For example, without using Ctrl-F, how long does it take you to tell me what the `preexec_fn` parameter of [`subprocess.Popen`](https://docs.python.org/3/library/subprocess.html?#subprocess.Popen) do?
6. Dependency on the operating system. Python presents itself as a very high-level language. However, if you e.g. try to capture the output of a subprocess into `io.StringIO`, it will fail with `io.UnsupportedOperation: fileno` because `io.StringIO` does not have a file descriptor.

In 2014, I wrote a [Czech blog post](https://cs-blog.petrzemek.net/2014-10-26-co-se-mi-nelibi-na-pythonu) that gives you the details.
