### ISSUE TITLE
30 questions

### ISSUE THREAD

**Issue by MrAndyR** [s3rvac/AMA#3]
I greet you @ s3rvac.

(I hope these are not too personal or inappropriate in any way. Otherwise, i apologize )
My questions would be the following:

1.  How was your school and professional career so far?
2. Do you have a degree, if so, in what and at which university were you?
3.  Do you also play PC / console games as a software developer?
4.  What do you personally think about cloud gaming?
5.   What is the best and most difficult part of this job as a software developer?
6.  Do you also have contacts to the gaming industry, and if so, which studios?
7.  For Windows 10 there are special themes / designs or skins that can be used. In your opinion, how long does it take to create such a skin / theme?
8. What is your everyday life like as a software developer?
9. What are the typical working hours (from when to when do you work)?
10. When talking about games and the locking of the hardware ID, how exactly can you imagine how this leads to the lock?
11. Does a software developer also have to do with the security of the software that the software is protected against hackers?
12. Do you have a large circle of friends working in the software / hardware industry?
13. What do you think of the digital age in the future? Since everything is almost only converted to digital (sick leave from the doctor)
14. Have you already worked with the next-gen console, if so, how was your experience there?
15. If not, what do you think of the next console generation? Will it be tough competition for the Pc and is the Pc at risk?
16. Do you know anything about the following:
Is it possible to integrate a direct 1: 1 mouse and keyboard support into the consoles via adapter or other solutions, the mouse and keyboard feel exactly like on the PC?
17. There are different types of software developers. What kind of software developer is best suited for the future, with a secure job and a high salary?
18. Which job would you say is the most difficult in the gaming industry or in general in IT?
19. Do you also travel a lot or rather little, if yes to which countries?
20. Is life in the Czech Republic good or bad?
21. Do you have family, what does this say about your job?
22. Which customer types (special companies, rich people ..) have you had contact with so far?
23. Can you tell me why some internet browsers do everything on cloud services?
For example: If you want bookmarks to be secure, this only works via cloud services. In the past, you could simply export the bookmarks as an .html file.
24. Is it difficult to create an app for a smartphone ( bookmark backup .html App)?
25. Are you on social networks like Facebook, Instagram & Co? What do you make of it?
26. As a software developer, you have a large work space with expensive  elevated equipment?
27. Do you work alone or in a company?
28. Have you ever had a problem where you needed advice from another expert, if so, what was the case exactly?
29. Would you change something in your life, if so what?
30. What plans (career, life, ..) do you have in the future?

Then I say thank you in advance.
I hope there are not too many questions ;) .

**Comment by s3rvac** [comment]
> 1. How was your school and professional career so far?

I studied at a grammar school from 2001 to 2005, then M.Sc. at [Faculty of Information Technology, Brno University of Technology](https://www.fit.vut.cz/) from 2005 to 2010, and then Ph.D. at the same university from 2010 to 2014. As for my professional career as a software developer, I worked from 2011 to 2016 at [AVG Technologies](https://www.avg.com), and then since 2016 I have been working at [Avast](https://www.avast.com/).

> 2. Do you have a degree, if so, in what and at which university were you?

I have a Ph.D. in computer science from [Faculty of Information Technology, Brno University of Technology](https://www.fit.vut.cz/).

> 3. Do you also play PC / console games as a software developer?

I used to play PC games from around 1992 to 2005 (even competitive ones), but I do not play them anymore.

> 4. What do you personally think about cloud gaming?

I had to look that up [on wikipedia](https://en.wikipedia.org/wiki/Cloud_gaming). I do not have any opinion on that.

> 5. What is the best and most difficult part of this job as a software developer?

The best: A creative job where you create something out of nothing, solve interesting problems, and learn how things work.

The most difficult: Managing complexity and dealing with possible errors and security issues in the software.

> 6. Do you also have contacts to the gaming industry, and if so, which studios?

None.

> 7. For Windows 10 there are special themes / designs or skins that can be used. In your opinion, how long does it take to create such a skin / theme?

No idea. I do not use Windows 10 nor have much experience with creating themes.

> 8. What is your everyday life like as a software developer?

I usually wake up at 05:00, take a shower, have breakfast, and go to work. In there, I sit or stand whilst working on a PC and communicating with others in my team and at the company. I work from 06:00-07:00 to 14:00-15:00 (8 hours a day on average) with lunch around 11:00. After I get home, I do my chores, exercise, go out, do programming, write blog posts, learn new things, read books, watch movies etc. I have dinner around 18:00 and go to sleep around 21:00.

> 9. What are the typical working hours (from when to when do you work)?

See the previous answer.

> 10. When talking about games and the locking of the hardware ID, how exactly can you imagine how this leads to the lock?

I am sorry, I do not know what that means.

> 11. Does a software developer also have to do with the security of the software that the software is protected against hackers?

Definitely. It is one of the most important parts of software development.

> 12. Do you have a large circle of friends working in the software / hardware industry?

I guess all my friends work in IT.

> 13. What do you think of the digital age in the future? Since everything is almost only converted to digital (sick leave from the doctor)

I like that we are moving away from paper to digital. Digital documents do not take that much physical space and are easily searchable.

> 14. Have you already worked with the next-gen console, if so, how was your experience there?

No.

> 15. If not, what do you think of the next console generation? Will it be tough competition for the Pc and is the Pc at risk?

I think PCs are here to stay.

> 16. Do you know anything about the following: Is it possible to integrate a direct 1: 1 mouse and keyboard support into the consoles via adapter or other solutions, the mouse and keyboard feel exactly like on the PC?

No.

> 17. There are different types of software developers. What kind of software developer is best suited for the future, with a secure job and a high salary?

I would probably say developers with mathematical and AI/ML background because AI/ML has been gaining a lot of traction.

> 18. Which job would you say is the most difficult in the gaming industry or in general in IT?

I can't tell for the gaming industry, but in general in IT, I believe the most difficult job is working on mission-critical systems, like aircraft navigation, nuclear reactors, or systems used in healthcare.

> 19. Do you also travel a lot or rather little, if yes to which countries?

I do not travel much.

> 20. Is life in the Czech Republic good or bad?

When compared to what is happening in other countries, I think we have a pretty good life here.

> 21. Do you have family, what does this say about your job?

I am sorry, I do not understand this question.

> 22. Which customer types (special companies, rich people ..) have you had contact with so far?

None. I have been working exclusively on internal tools and systems.

> 23. Can you tell me why some internet browsers do everything on cloud services? For example: If you want bookmarks to be secure, this only works via cloud services. In the past, you could simply export the bookmarks as an .html file.

I think there are two reasons: (1) It is easier for users and (2) Internet companies can have access to user data and use them to profit.

> 24. Is it difficult to create an app for a smartphone ( bookmark backup .html App)?

No idea. I have never done any development on mobile platforms.

> 25. Are you on social networks like Facebook, Instagram & Co? What do you make of it?

No. I have compared their pros and cons, and they do not provide enough advantages to me to make up for their disadvantages. The only social network that I occasionally use is [Twitter](https://twitter.com/s3rvac), but only for technical content.

> 26. As a software developer, you have a large work space with expensive elevated equipment?

I think that depends on the definition of _expensive_. I have a height-adjustable desk measuring about 160x75 cm, comfortable chair, PC/notebook, two monitors, keyboard, mouse, mousepad, and headphones.

> 27. Do you work alone or in a company?

At a company.

> 28. Have you ever had a problem where you needed advice from another expert, if so, what was the case exactly?

All the time ;-). I either ask them personally (if there is such an expert at the company), or use community forums on the Internet.

> 29. Would you change something in your life, if so what?

I can't think of anything. I am happy with my life choices so far.

> 30. What plans (career, life, ..) do you have in the future?

I want to learn a lot more than I know now (I am a knowledge worker after all), gain more skills with newer programming languages and technologies, invest more time and craft into building open-source software, do more writing, lecturing and talks, and become more visible in the software-development world.
